const { GoogleGenAI } = require("@google/genai");
const { z } = require("zod");
const { zodToJsonSchema } = require("zod-to-json-schema");
const puppeteer = require("puppeteer");

const genAI = new GoogleGenAI({
  apiKey: process.env.GOOGLE_GENAI_API_KEY
});

// Reusable helper
async function generateContent({ prompt, config = {} }) {
  const result = await genAI.models.generateContent({
    model: "gemini-2.5-flash",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
      ...config
    }
  });

  return result;
}

let browser = null;

async function getBrowser() {
  if (!browser) {
    browser = await puppeteer.launch({
      headless: "new",
      args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-dev-shm-usage"
      ]
    });
  }
  return browser;
}

async function generatePdfFromHtml(htmlContent) {
  const browserInstance = await getBrowser();
  const page = await browserInstance.newPage();

  try {
    page.setDefaultTimeout(60000);
    page.setDefaultNavigationTimeout(60000);

    await page.setContent(htmlContent, { waitUntil: "domcontentloaded", timeout: 30000 });
    await page.emulateMediaType("screen");

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: {
        top: "20mm",
        bottom: "20mm",
        left: "15mm",
        right: "15mm"
      }
    });

    return pdfBuffer;
  } finally {
    await page.close();
  }
}

const interviewReportSchema = z.object({
  title: z.string().describe("The title of the job for which the interview report is generated"),
  matchScore: z.number().min(0).max(100),
  technicalQuestions: z.array(
    z.object({
      question: z.string(),
      intention: z.string(),
      answer: z.string()
    })
  ).min(1),
  behavioralQuestions: z.array(
    z.object({
      question: z.string(),
      intention: z.string(),
      answer: z.string()
    })
  ).min(1),
  skillGaps: z.array(
    z.object({
      skill: z.string(),
      severity: z.enum(["low", "medium", "high"])
    })
  ).min(1),
  preparationPlan: z.array(
    z.object({
      day: z.number().int().min(1),
      focus: z.string(),
      tasks: z.array(z.string()).min(1)
    })
  ).min(1)
});

async function generateInterviewReport({ resume, selfDescription, jobDescription, title }) {
  const prompt = `
Create a complete interview report in JSON only.

Return exactly this structure:
{
  "title": "string",
  "matchScore": number,
  "technicalQuestions": [
    { "question": "string", "intention": "string", "answer": "string" }
  ],
  "behavioralQuestions": [
    { "question": "string", "intention": "string", "answer": "string" }
  ],
  "skillGaps": [
    { "skill": "string", "severity": "low" | "medium" | "high" }
  ],
  "preparationPlan": [
    { "day": number, "focus": "string", "tasks": ["string"] }
  ]
}

Rules:
- Return JSON only.
- Arrays must contain objects only.
- Do not return strings inside arrays.
- Do not return empty arrays.

Resume: ${resume}
Self Description: ${selfDescription}
Job Description: ${jobDescription}
Job Title: ${title}
`;

  const result = await generateContent({ prompt });

  const responseText = result.text || "";
  const cleanJson = responseText.replace(/```json/g, "").replace(/```/g, "").trim();
  const parsed = JSON.parse(cleanJson);

  return interviewReportSchema.parse(parsed);
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {
  try{
  const resumePdfSchema = z.object({
    html: z.string().describe("The HTML content of the resume which can be converted to PDF using puppeteer")
  });

  const prompt = `
Generate resume for a candidate with the following details:
Resume: ${resume}
Self Description: ${selfDescription}
Job Description: ${jobDescription}

The response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using puppeteer.

The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience.
The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
The content of resume should not sound like it's generated by AI and should be as close as possible to a real human-written resume.
You can highlight the content using some colors or different font styles but the overall design should be simple and professional.
The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF.
Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
`;

  const result = await generateContent({
    prompt,
    config: { responseSchema: zodToJsonSchema(resumePdfSchema) }
  });

  const cleanText = (result.text || "").replace(/```json/g, "").replace(/```/g, "").trim();
  const jsonContent = JSON.parse(cleanText);

  const pdfBuffer = await generatePdfFromHtml(jsonContent.html);
  return pdfBuffer;
}
catch (error) {
    console.log("EXACT ERROR:", error.message)  
    throw error
  }
}

module.exports = {
  generateInterviewReport,
  generateResumePdf
};